name: Deploy Flutter Web to GitHub Pages

on:
  push:
    branches:
      - main  # Troque para o branch que você está usando

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Código
        uses: actions/checkout@v3

      - name: Instalar Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 'stable'

      - name: Rodar Flutter Build Web
        run: flutter build web

      - name: Deploy para GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: build/web
